# Generated by Django 5.2.13 on 2026-04-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Stationery', 'Stationery'), ('Furniture', 'Furniture')], max_length=50)),
                ('quantity_in_stock', models.IntegerField()),
                ('storage_aisle', models.CharField(max_length=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
